export const ORDER_STATUS = {
  PLANNED: 'PLANNED',
  VALIDATED: 'VALIDATED',
  ENRICHED: 'ENRICHED',
  PLACED: 'PLACED',
  BULKED: 'BULKED',
  TRANSMITTED: 'TRANSMITTED',
  CONFIRMED: 'CONFIRMED',
  CONTRACTED: 'CONTRACTED',
  BOOKED: 'BOOKED',
  ERRORED: 'ERRORED',
}

export const ORDER_SIDE = {
  BUY: 'BUY',
  SELL: 'SELL',
}

export const STATUS_GROUP = {
  PROCESSING: ['PLANNED', 'VALIDATED', 'ENRICHED', 'PLACED'],
  PENDING: ['BULKED', 'TRANSMITTED', 'CONFIRMED', 'CONTRACTED'],
  COMPLETED: ['BOOKED'],
  FAILED: ['ERRORED'],
}

export const STATUS_LABEL = {
  PLANNED: 'Planned',
  VALIDATED: 'Validated',
  ENRICHED: 'Enriched',
  PLACED: 'Placed',
  BULKED: 'Grouped',
  TRANSMITTED: 'Transmitted',
  CONFIRMED: 'Confirmed',
  CONTRACTED: 'Contracted',
  BOOKED: 'Completed',
  ERRORED: 'Failed',
}

